### PR TITLE
Update CircleHash to newer version

### LINKED ISSUE #243: Update to latest version of CircleHash64 for faster speed
### Issue To Be Solved

I optimized [fxamacker/circlehash](https://github.com/fxamacker/circlehash) over the weekend.  Optimizations are fully backward compatible and speedup short input sizes, especially on Go 1.17 or newer.

### Suggested Solution

Update to optimized CircleHash64.

Add the following table to README with explanation of hash algorithm choices.

### Atree uses CircleHash64 with deferred+segmented BLAKE3 for collisions
Atree uses CircleHash64 because hash inputs are currently very small (usually < 64 bytes).

|              | CircleHash64 🏅<br/>(seeded) | SipHash <br/>(seeded) | BLAKE3 🏅<br/>(crypto) | SHA3-256 <br/>(crypto) |
|:-------------|:---:|:---:|:---:|:---:|
| 4 bytes | 1.34 GB/s | 0.361 GB/s | 0.027 GB/s | 0.00491 GB/s |
| 8 bytes | 2.70 GB/s | 0.642 GB/s | 0.106 GB/s | 0.00984 GB/s |
| 16 bytes | 5.48 GB/s | 1.03 GB/s | 0.217 GB/s | 0.0197 GB/s |
| 32 bytes | 8.01 GB/s | 1.46 GB/s | 0.462 GB/s | 0.0399 GB/s |
| 64 bytes | 10.3 GB/s | 1.83 GB/s | 0.911 GB/s | 0.0812 GB/s |
| 128 bytes | 12.8 GB/s | 2.09 GB/s | 1.03 GB/s | 0.172 GB/s |
| 192 bytes | 14.2 GB/s | 2.17 GB/s | 1.04 GB/s | 0.158 GB/s |
| 256 bytes | 15.0 GB/s | 2.22 GB/s | 1.06 GB/s | 0.219 GB/s |

- Using Go 1.17.7, darwin_amd64, i7-1068N7 CPU
- Results are from `go test -bench=. -count=20` and `benchstat`
- Some hash libraries have slowdowns at some larger sizes (they are not a typo).

### PR DESCRIPTION
**Pull request by fxamacker**
## Description

- Update to newer version of CircleHash64 which is faster and 100% backward compatible.
- Update README to add section "OMT uses CircleHash64 with Deferred+Segmented BLAKE3 Digests"
    - Show comparison of CircleHash64 vs SipHash, and BLAKE3 vs SHA3-256 to help explain our algorithm choices

Closes #243 

______

- [x] Targeted PR against `main` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/atree/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by turbolent — APPROVED** [review]
Nice! 

In case we do not already have some, maybe it would be great to have some regression tests here in atree that assert expected hash output for some values

**Comment by fxamacker** [comment]
> In case we do not already have some, maybe it would be great to have some regression tests here in atree that assert expected hash output for some values

@turbolent That's a great idea!  I'm going to include that before merging this PR.

**Review by ramtinms — APPROVED** [review]

**Comment by fxamacker** [comment]
I opened PR https://github.com/onflow/atree/pull/247 to add regression/compatibility test. It's a subset of tests copied from [circlehash](https://github.com/fxamacker/circlehash).

**Review by ramtinms — APPROVED** [review]

**Review by turbolent — APPROVED** [review]

**Comment by turbolent** [comment]
@fxamacker Please feel free to merge, I also approved #247

**Pull request merged**
